In [1]:
from pyspark.sql import SparkSession
# May take a little while on a local computer
spark = SparkSession.builder.appName("dates").getOrCreate()

In [2]:
import pandas as pd
#df=pd.read_csv()
url = 'https://raw.githubusercontent.com/tirthajyoti/Spark-with-Python/master/Data/appl_stock.csv'
df = pd.read_csv(url, index_col=1)
print(df.head(5))

In [3]:
df1 = spark.createDataFrame(df)
df1.show()

In [4]:
from pyspark.sql.functions import format_number,dayofmonth,hour,dayofyear,month,year,weekofyear,date_format

In [5]:
df1.printSchema()

In [6]:
from pyspark.sql.types import *
# Change column type
df_new = df1.withColumn("Date", df1["Date"].cast(DateType()))
df_new.printSchema()
#df['Date'])).show()

In [7]:
df1.select(dayofmonth(df1['Date'])).show()

In [8]:
df1.select(hour(df1['Date'])).show()

In [9]:
df1.select(dayofyear(df1['Date'])).show()

In [10]:
df1.select(month(df1['Date'])).show()

In [11]:
df1.select(year(df1['Date'])).show()

In [12]:
df1.withColumn("Year",year(df1['Date'])).show()

In [13]:
newdf = df1.withColumn("Year",year(df1['Date']))
newdf.groupBy("Year").mean()[['avg(Year)','avg(Close)']].show()

In [14]:
result = newdf.groupBy("Year").mean()[['avg(Year)','avg(Close)']]
result = result.withColumnRenamed("avg(Year)","Year")
result = result.select('Year',format_number('avg(Close)',2).alias("Mean Close")).show()